export = MoneroDaemonInfo;
/**
 * Monero daemon info.
 */
declare class MoneroDaemonInfo {
    constructor(state: any);
    state: any;
    toJson(): any;
    getVersion(): any;
    setVersion(version: any): this;
    getNumAltBlocks(): any;
    setNumAltBlocks(numAltBlocks: any): this;
    getBlockSizeLimit(): any;
    setBlockSizeLimit(blockSizeLimit: any): this;
    getBlockSizeMedian(): any;
    setBlockSizeMedian(blockSizeMedian: any): this;
    getBlockWeightLimit(): any;
    setBlockWeightLimit(blockWeightLimit: any): this;
    getBlockWeightMedian(): any;
    setBlockWeightMedian(blockWeightMedian: any): this;
    getBootstrapDaemonAddress(): any;
    setBootstrapDaemonAddress(bootstrapDaemonAddress: any): this;
    getDifficulty(): any;
    setDifficulty(difficulty: any): this;
    getCumulativeDifficulty(): any;
    setCumulativeDifficulty(cumulativeDifficulty: any): this;
    getFreeSpace(): any;
    setFreeSpace(freeSpace: any): this;
    getNumOfflinePeers(): any;
    setNumOfflinePeers(numOfflinePeers: any): this;
    getNumOnlinePeers(): any;
    setNumOnlinePeers(numOnlinePeers: any): this;
    getHeight(): any;
    setHeight(height: any): this;
    getHeightWithoutBootstrap(): any;
    setHeightWithoutBootstrap(heightWithoutBootstrap: any): this;
    getNetworkType(): any;
    setNetworkType(networkType: any): this;
    isOffline(): any;
    setIsOffline(isOffline: any): this;
    getNumIncomingConnections(): any;
    setNumIncomingConnections(numIncomingConnections: any): this;
    getNumOutgoingConnections(): any;
    setNumOutgoingConnections(numOutgoingConnections: any): this;
    getNumRpcConnections(): any;
    setNumRpcConnections(numRpcConnections: any): this;
    getStartTimestamp(): any;
    setStartTimestamp(startTimestamp: any): this;
    getAdjustedTimestamp(): any;
    setAdjustedTimestamp(adjustedTimestamp: any): this;
    getTarget(): any;
    setTarget(target: any): this;
    getTargetHeight(): any;
    setTargetHeight(targetHeight: any): this;
    getTopBlockHash(): any;
    setTopBlockHash(topBlockHash: any): this;
    getNumTxs(): any;
    setNumTxs(numTxs: any): this;
    getNumTxsPool(): any;
    setNumTxsPool(numTxsPool: any): this;
    getWasBootstrapEverUsed(): any;
    setWasBootstrapEverUsed(wasBootstrapEverUsed: any): this;
    getDatabaseSize(): any;
    setDatabaseSize(databaseSize: any): this;
    getUpdateAvailable(): any;
    setUpdateAvailable(updateAvailable: any): this;
    getCredits(): any;
    setCredits(credits: any): this;
    isBusySyncing(): any;
    setIsBusySyncing(isBusySyncing: any): this;
    isSynchronized(): any;
    setIsSynchronized(isSynchronized: any): this;
    isRestricted(): any;
    setIsRestricted(isRestricted: any): this;
}
