module.exports = function() {
  this.assert = require("assert");
  this.GenUtils = require("../../utils/GenUtils");
  this.BigInteger = require("../../../../../external/mymonero-core-js/cryptonote_utils/biginteger").BigInteger;
  this.Filter = require("../../utils/Filter");
  this.MoneroError = require("../../utils/MoneroError");
  this.MoneroUtils = require("../../utils/MoneroUtils");
  this.MoneroRpcConnection = require("../../rpc/MoneroRpcConnection");
  this.MoneroRpcError = require("../../rpc/MoneroRpcError");
  
  this.MoneroAltChain = require("./MoneroAltChain");
  this.MoneroBan = require("./MoneroBan");
  this.MoneroBlock = require("./MoneroBlock");
  this.MoneroBlockHeader = require("./MoneroBlockHeader");
  this.MoneroBlockTemplate = require("./MoneroBlockTemplate");
  this.MoneroDaemonConnection = require("./MoneroDaemonConnection");
  this.MoneroDaemonConnectionSpan = require("./MoneroDaemonConnectionSpan");
  this.MoneroDaemonInfo = require("./MoneroDaemonInfo");
  this.MoneroDaemonModel = require("./MoneroDaemonModel");
  this.MoneroDaemonPeer = require("./MoneroDaemonPeer");
  this.MoneroDaemonSyncInfo = require("./MoneroDaemonSyncInfo");
  this.MoneroDaemonUpdateCheckResult = require("./MoneroDaemonUpdateCheckResult");
  this.MoneroDaemonUpdateDownloadResult = require("./MoneroDaemonUpdateDownloadResult");
  this.MoneroHardForkInfo = require("./MoneroHardForkInfo");
  this.MoneroKeyImage = require("./MoneroKeyImage");
  this.MoneroKeyImageSpentStatus = require("./MoneroKeyImageSpentStatus");
  this.MoneroMinerTxSum = require("./MoneroMinerTxSum");
  this.MoneroMiningStatus = require("./MoneroMiningStatus");
  this.MoneroNetworkType = require("./MoneroNetworkType");
  this.MoneroOutput = require("./MoneroOutput");
  this.MoneroOutputHistogramEntry = require("./MoneroOutputHistogramEntry");
  this.MoneroSubmitTxResult = require("./MoneroSubmitTxResult");
  this.MoneroTx = require("./MoneroTx");
  this.MoneroTxPoolStats = require("./MoneroTxPoolStats");
}